env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- id: githubinfo
  env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  ignore:
    - goos: darwin
      goarch: 386
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
