name: Test

on: push

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lint
      uses: shoukoo/golang-pipeline/go1.13/linter@master
    - name: test
      uses: shoukoo/golang-pipeline/go1.13/test@master
